_check_cmd git
if test $? -eq 0; then
  #alias git-push-current-branch='git push origin \`git status | grep \'On branch\' | awk \'\{print \$4\}\'\`'
  alias git-init='git init'
  alias git-clone='git clone'
  alias git-fsck='git fsck'
  alias git-fsck-full='git fsck --full'
  alias git-gc='git gc'
  alias git-status='git status'
  alias git-add='git add'
  alias git-diff='git diff'
  alias git-commit='git commit'
  alias git-commit-m='git commit -m'
  alias git-commit-c-ORIG_HEAD='git commit -c ORIG_HEAD'
  alias git-commit-c-ORIG_HEAD-m='git commit -c ORIG_HEAD -m'
  alias git-commit-amend='git commit --amend'
  alias git-commit-amend-m='git commit --amend -m'
  alias git-log='git log'
  alias git-push='git push'
  alias git-push-origin-master='git push origin master'
  alias git-push-origin-develop='git push origin develop'
  alias git-push-origin-pre_develop='git push origin pre_develop'
  alias git-fetch='git fetch'
  alias git-pull='git pull'
  alias git-pull-rebase='git pull --rebase'
  alias git-rebase='git rebase'
  alias git-branch='git branch'
  alias git-checkout='git checkout'
  alias git-checkout-b='git checkout -b'
  alias git-show-branch='git show-branch'
  alias git-merge='git merge'
  alias git-merge-no-ff='git merge --no-ff'
  alias git-reset='git reset'
  alias git-reset-hard-HEAD='git reset --hard HEAD'
  alias git-reset-soft-HEAD='git reset --soft HEAD'
  alias git-diff-ORIG_HEAD='git diff ORIG_HEAD'
  alias git-revert='git revert'
  alias git-tag='git tag'
  alias git-stash='git stash'
  alias git-stash-pop='git stash pop'
  alias git-stash-list='git stash list'
fi

