_check_cmd VBoxManage
if test $? -eq 0; then
  vboxmanage=`which -a VBoxManage | egrep '^/' | head -1`

  alias vboxmanage="${vboxmanage}"
  alias vboxmanage-list-vms="${vboxmanage} list vms"
  alias vboxmanage-list-running-vms="${vboxmanage} list runningvms"
  alias vboxmanage-list-os-types="${vboxmanage} list ostypes"
  alias vboxmanage-list-host-dvds="${vboxmanage} list hostdvds"
  alias vboxmanage-list-host-floppies="${vboxmanage} list hostfloppies"
  alias vboxmanage-list-bridged-ifs="${vboxmanage} list bridgedifs"
  alias vboxmanage-list-hostonly-ifs="${vboxmanage} list hostonlyifs"
  alias vboxmanage-list-dhcp-servers="${vboxmanage} list dhcpservers"
  alias vboxmanage-list-host-info="${vboxmanage} list hostinfo"
  alias vboxmanage-list-host-cpu-ids="${vboxmanage} list hostcpuids"
  alias vboxmanage-list-hdd-backends="${vboxmanage} list hddbackends"
  alias vboxmanage-list-hdds="${vboxmanage} list hdds"
  alias vboxmanage-list-dvds="${vboxmanage} list dvds"
  alias vboxmanage-list-floppies="${vboxmanage} list floppies"
  alias vboxmanage-list-usb-host="${vboxmanage} list usbhost"
  alias vboxmanage-list-usb-filters="${vboxmanage} list usbfilters"
  alias vboxmanage-list-system-properties="${vboxmanage} list systemproperties"
  alias vboxmanage-show-vm-info="${vboxmanage} showvminfo"
  alias vboxmanage-register-vm="${vboxmanage} registervm"
  alias vboxmanage-unregister-vm="${vboxmanage} unregistervm"
  alias vboxmanage-create-vm="${vboxmanage} createvm"
  alias vboxmanage-modify-vm="${vboxmanage} modifyvm"
  alias vboxmanage-import="${vboxmanage} import"
  alias vboxmanage-export="${vboxmanage} export"
  alias vboxmanage-start-vm="${vboxmanage} startvm"
  alias vboxmanage-control-vm="${vboxmanage} controlvm"
  alias vboxmanage-discard-state="${vboxmanage} discardstate"
  alias vboxmanage-adopt-state="${vboxmanage} adoptstate"
  alias vboxmanage-snapshot="${vboxmanage} snapshot"
  alias vboxmanage-open-medium="${vboxmanage} openmedium"
  alias vboxmanage-close-medium="${vboxmanage} closemedium"
  alias vboxmanage-storage-attach="${vboxmanage} storageattach"
  alias vboxmanage-storage-ctl="${vboxmanage} storagectl"
  alias vboxmanage-show-hd-info="${vboxmanage} showhdinfo"
  alias vboxmanage-create-hd="${vboxmanage} createhd"
  alias vboxmanage-modify-hd="${vboxmanage} modifyhd"
  alias vboxmanage-clone-hd="${vboxmanage} clonehd"
  alias vboxmanage-convert-from-raw="${vboxmanage} convertfromraw"
  alias vboxmanage-add-iscsi-disk="${vboxmanage} addiscsidisk"
  alias vboxmanage-get-extra-data="${vboxmanage} getextradata"
  alias vboxmanage-set-extra-data="${vboxmanage} setextradata"
  alias vboxmanage-set-property="${vboxmanage} setproperty"
  alias vboxmanage-usb-filter="${vboxmanage} usbfilter"
  alias vboxmanage-shared-folder="${vboxmanage} sharedfolder"
  alias vboxmanage-vm-statistics="${vboxmanage} vmstatistics"
  alias vboxmanage-guest-property="${vboxmanage} guestproperty"
  alias vboxmanage-metrics="${vboxmanage} metrics"
  alias vboxmanage-hostonly-if="${vboxmanage} hostonlyif"
  alias vboxmanage-dhcp-server="${vboxmanage} dhcpserver"

  unset vboxmanage
fi

